Cu 86c0810e0 create user endpoint
Let-s-build-something/enrichment-api pull request #2
Opened 2024-09-08 22:40 UTC by zeddosx

2024-09-08 22:40 UTC, JacobCube commented
Task linked: [CU-86c0810e0 Create user endpoint](https://app.clickup.com/t/86c0810e0)

2024-09-09 15:39 UTC, zeddosx commented
Shiet, tak ještě ne, proběhla úprava zadání.

2024-09-09 21:35 UTC, zeddosx commented
@Blazik Could you please check this out if it is fine?

2024-09-10 18:36 UTC, Blazik requested changes

2024-09-10 18:36 UTC, Blazik commented on src/endpoints/create_user.rs
> +#[post("/create_user")]
I think we should follow REST API design, which means this endpoint should be `/users`

2024-09-10 18:36 UTC, Blazik commented on src/endpoints/create_user.rs
> +        Ok(_user) => HttpResponse::Created().json(json_response),
instead of `_user`, you can omit the name completely with just `_`, so `Ok(_) => ...`

2024-09-10 18:36 UTC, Blazik commented on src/endpoints/create_user.rs
> +        email: sea_orm::ActiveValue::set(Option::from(data.email.clone())),
you should not need Option::from, because Option is already in `data.email`

2024-09-10 18:36 UTC, Blazik commented on src/endpoints/create_user.rs
> +    let timestamp = start.duration_since(UNIX_EPOCH)
have you looked at `chrono` library? it provides useful functions, like this timestamp would be `chrono::Local::now().timestamp()`, or maybe even better sending time in UTC `chrono::Utc::now().timestamp()`

2024-09-10 18:54 UTC, zeddosx commented
Fixed everything + imported a few classes to the users.rs file

2024-09-10 19:07 UTC, Blazik approved these changes
LGTM

2024-09-10 19:07 UTC, merged