Cu 86c0b47vq fcm tokens from client side  - be
Let-s-build-something/enrichment-api pull request #6
Opened 2024-09-19 22:40 UTC by zeddosx

2024-09-19 22:40 UTC, JacobCube commented
Task linked: [CU-86c0b47vq FCM tokens from client side - BE](https://app.clickup.com/t/86c0b47vq)

2024-09-20 09:42 UTC, JacobCube commented on migration/src/enums.rs
> +pub enum Platform {
okomentovat alespoň tím, že Native je iOS + macOS + watchOS + AppleTV
Jvm je Linux + Windows

2024-09-20 09:42 UTC, JacobCube commented on migration/src/m20240919_192832_user_fcm_tokens.rs
> +enum UserFcmToken {
není to duplicitní s `pub enum User {`?

2024-09-20 14:35 UTC, zeddosx commented on migration/src/m20240919_192832_user_fcm_tokens.rs
> +enum UserFcmToken {
Jestli myslíš to v té druhé migraci tak nee.

2024-09-21 09:09 UTC, Blazik requested changes

2024-09-21 09:09 UTC, Blazik commented on migration/src/m20240908_220626_user.rs
> +                    )
you cannot edit existing migration because it was already run on server, pls make a new one where you add these columns

2024-09-21 09:09 UTC, Blazik commented on src/endpoints/users.rs
> +    let result = user.clone().insert(db.get_ref()).await;
`.clone()` is not needed here

2024-09-21 09:09 UTC, Blazik commented on src/endpoints/users.rs
> +            if let Some(fcm_token) = data.fcm_token.clone() {
`.clone()` is not needed here, you can only borrow `fcm_token` like so 
```rust
if let Some(ref fcm_token) = data.fcm_token {
```

2024-09-21 09:09 UTC, Blazik commented on src/endpoints/users.rs
> +                        fcm_token: sea_orm::ActiveValue::set(data.fcm_token.clone().unwrap()),
here you can use the variable `fcm_token` -> `fcm_token.to_owned()`

2024-09-21 12:02 UTC, Blazik approved these changes

2024-09-21 12:02 UTC, merged